### ISSUE TITLE
ARM cortex-M4 compiler option for coremark-pro benchmark

### ISSUE THREAD

**Issue by sunildogra1710** [eembc/coremark-pro#18]
Hi, 
i am able to build coremark-pro with Ubuntu with "gcc-linaro-11.3.1-2022.06-x86_64_arm-linux-gnueabihf". 

Could you please suggest recommended cortex-M4 compiler option for coremark-pro.

**Comment by petertorelli** [comment]
Hello,
I'm closing this request because while this is a good question, it is not related to the functionality of CoreMark-PRO (e.g., bug or performance issue). I would recommend the [Arm GCC developer website](https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain) for their documentation.
Peter
