### ISSUE TITLE
Question about the iteration count in the kernel of "cjpeg-rose7-preset"

### ISSUE THREAD

**Issue by javaddict** [eembc/coremark-pro#5]
In the [main()](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/workloads/cjpeg-rose7-preset/cjpeg-rose7-preset.c#L86) of workload "cjpeg-rose7-preset", I see a lot of calls to [helper_cjpegrose7preset()](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/workloads/cjpeg-rose7-preset/cjpeg-rose7-preset.c#L8) where **repeats_override** is given **1**. Then at [this line](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/workloads/cjpeg-rose7-preset/cjpeg-rose7-preset.c#L15), leading to [these lines](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/mith/src/mith_workload.c#L34-L35), we know **tcdef->iterations** is thus set to **1**.

When this workload is run, kernel [t_run_test_cjpeg()](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L269) is executed.
According to [this line](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L278), **override** is **1**.
Therefore **tcdef->rec_iterations** will not be used ([this line](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L283)).

**tcdef->rec_iterations** is configured [here](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L279) and is supposed to be the "recommended" iteration count according to [this](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L153) and [this](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/algo.h#L112).

I wonder, why is **repeats_override** not given **0** to have the recommended value used?

(BTW, the kernel of other workloads does not use **tcdef->iterations**.)

**Comment by petertorelli** [comment]
@javaddict Thanks for the question, and for taking the time to document your thought process and link to the code. Good sluething!

The short answer is: None of the values you followed are used! The default number of iterations is determined by the `workloads` structure when it is defined in each of the files found in `./workloads/*/*.c`:

~~~
% egrep 'workload->iterations=\d+;' ./workloads/*/*.c
./workloads/cjpeg-rose7-preset/cjpeg-rose7-preset.c:	workload->iterations=10;
./workloads/core/core.c:	workload->iterations=1;
./workloads/linear_alg-mid-100x100-sp/linear_alg-mid-100x100-sp.c:	workload->iterations=50;
./workloads/loops-all-mid-10k-sp/loops-all-mid-10k-sp.c:	workload->iterations=50;
./workloads/nnet_test/nnet_test.c:	workload->iterations=10;
./workloads/parser-125k/parser-125k.c:	workload->iterations=1;
./workloads/parser-125k/parser-500k.c:	workload->iterations=1;
./workloads/radix2-big-64k/radix2-big-64k.c:	workload->iterations=1000;
./workloads/sha-test/sha-test.c:	workload->iterations=10;
./workloads/zip-test/zip-test.c:	workload->iterations=1;
~~~

If the user specifies `-i` on the command line, e.g., `-i100`, that will override the workload iterations in the top-level workload file.
~~~
    :
    th_parse_flag_unsigned(argc,argv,"-i",&workload->iterations);
    :
~~~

The number of iterations is then adjusted based on the number of contexts, OR if we are running in verification mode, `-v1`, it is forced to 1 (see the `mith_main_loop()` in `mith_lib.c` [here](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/mith/src/mith_lib.c#L252-L253)).

If you work backwards from the [result-printing function](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/mith/src/mith_lib.c#L445), you can see the evolution of `workloads->iterations`.

So now the obvious question: why are there so many references to iterations that aren't used?

That's partially due to EEMBC methodology, and partially due to the multithreaded nature of CoreMark-PRO.

First, methodology: we try to reuse as much code as possible without touching the underlying kernel functionality for maximum backwards compatibility. CoreMark-PRO is based on the composition of new and existing kernels, but with a new execution mode built on top: the Multi-Instance Test Harness (MITH).

Now, part two: since MITH deals with multiple threads and contexts, iteration management is a little trickier, so a higher-level variable was needed outside of the kernels. This is because each kernel may have a different number of iterations per thread vs. the entire benchmark. Consider the JPEG workload you are analyzing: `helper_cjpegrose7preset()` is called "a lot" because by default the workload uses a minimum of 8 worker threads. The worker threads are implemented as calls to the underlying kernel, which is not thread aware: instead, it is given a subset of the task. If you ran 10 iterations, you would not be able to call each worker thread 10 times and get correct results (because it makes no sense to do so since we work on one image per iteration)! You need 1 iteration per worker thread, x8 threads, run with the overall iterations, aka `workload->iterations`.

Does that make sense? I agree it is not inherently obvious without understanding some of the history, but we strictly do not to tamper with kernels once they have been released in a benchmark to maintain forward-consistency.

**Comment by javaddict** [comment]
I see. @petertorelli, thank you for the detailed explanation. 

If I understand correctly, the loop [here](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/benchmarks/consumer_v2/cjpeg/bmark_lite.c#L285-L288) is forced to 1 and the iteration is promoted outside the kernel, controlled by MITH through `-iN`(`workload->iterations`), `-cN`, `-wN`, etc.?

**Comment by petertorelli** [comment]
@javaddict Yes, that is correct.
